v1.1 workflow and small bugfix
SiLab-Bonn/aidatlu pull request #7
Opened 2024-12-13 11:49 UTC by rpartzsch

- bugfix for numpy version 2
- workflow with codestyle
- triggering edge display in h5 configuration

2024-12-13 12:50 UTC, cbespin requested changes

2024-12-13 12:50 UTC, cbespin commented on aidatlu/online_monitor/configuration.yaml
> +        frontend : tcp://131.220.165.88:1500
Use local address in repo

2024-12-13 12:50 UTC, cbespin commented on aidatlu/main/tlu.py
>          except:
I think it should be `except KeyboardInterrupt:` to catch the interrupt

2025-01-07 10:17 UTC, cbespin approved these changes

2025-01-07 11:51 UTC, lschall approved these changes

2025-01-07 11:53 UTC, merged